#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width 	1
bspc config window_gap          15

bspc config active_border_color '#273238'
bspc config normal_border_color '#273238'
bspc config focused_border_color '#ffffff'
bspc config presel_feedback_color '#273238'
bspc config pointer_follows_monitor true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle true

bspc rule -a firefox desktop='^2'
bspc rule -a chromium desktop='^3'
bspc rule -a Zathura state=tiled
bspc rule -a Ario desktop='^10' state=pseudo_tiled
bspc rule -a Thunar state=pseudo_tiled rectangle=750x450+0+0
